### PR TITLE
merge dev with master for guidestar change

### PR DESCRIPTION
**Pull request by aaron2382**
I think i did this right.

please check.

### CODE REVIEW

**Comment by DanielBodnar** [comment]
Hmm... this is merging a bunch of course that I think was already merged into master. Might want to double check after it's finished deploying

**Comment by aaron2382** [comment]
Ok, not where i wanted it. Trying again

**Comment by DanielBodnar** [comment]
Don't merge it into master until you've tested / reviewed in the staging environment. Heroku will create a temporary staging environment for every pull request, before it gets merged.

**Comment by aaron2382** [comment]
ummm shit.. i think i deleted the development branch. cannot see it.

This is why i shouldn't be doing this... I couldnt remember how to push it to the beta to see it

**Pull request merged**
